### ISSUE TITLE
Issue: Migrating from .env File to System Environment Variables

### ISSUE THREAD

**Issue by pratikbgit** [Improwised/nuxt3-boilerplate#19]
If you are using systemEnv variables instead of .env file variables then follow below PR process

**Comment by pratikbgit** [comment]
@shivani446 : Please add the necessary details so @payalraviya can easily add the necessary things.

**Comment by Jay-ponda-improwised** [comment]
@payalraviya https://github.com/just-containers/s6-overlay

**Comment by tapanbavaliya** [comment]
@pratikbgit What exactly we are trying to solve, what is expected **by adding S6 overlay**.

**Comment by pratikbgit** [comment]
@payalraviya : Got the context now she is working on that ticket.
Problem is not taking system variable.

**Comment by tapanbavaliya** [comment]
@pratikbgit can you please update ticket - Ty
